author:
  name: Miro Remias
  role: Product Leader
  bio: Bitcoiner, runner, father. 
  location: EU

social:
  - id: "x"
    label: "X"
    href: "https://x.com/mr21free"
  - id: "github"
    label: "GitHub"
    href: "https://github.com/mr21free"
  - id: "linkedin"
    label: "Linkedin"
    href: "https://www.linkedin.com/in/miroremias/"
  - id: "email"
    label: "Email"
    href: "mailto:miro.remias@foremsec.com"